export const books = [
  {
    id: 1,
    name: 'Billy Summers!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51f2iIrG6TL._AC_SX184_.jpg',
    author: 'Stephen King',
    cover: 'Hardcover',
    pages: '450',
    price: '499',
    story:
      'From legendary storyteller Stephen King, whose “restless imagination is a power that cannot be contained” (The New York Times Book Review), comes a thrilling new novel about a good guy in a bad job.',
    ratings: 4,
  },
  {
    id: 2,
    name: 'The 48 Laws of Power!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/41JIh4KMHRL._AC_SX184_.jpg',
    author: 'Robert Greene',
    cover: 'Paperback',
    pages: '300',
    price: '250',
    story:
      'Amoral, cunning, ruthless, and instructive, this multi-million-copy New York Times bestseller is the definitive manual for anyone interested in gaining, observing, or defending against ultimate control – from the author of The Laws of Human Nature.',
    ratings: 4.5,
  },
  {
    id: 3,
    name: 'The Madness of Crowd!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51Z1TpSzCwS._AC_SX184_.jpg',
    author: 'Louise Penny',
    cover: 'Hardcover',
    pages: '625',
    price: '300',
    story:
      'Chief Inspector Armand Gamache returns to Three Pines in #1 New York Times bestseller Louise Pennys latest spellbinding novel',
    ratings: 3.7,
  },
  {
    id: 4,
    name: 'Verity!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/41N1GA7CaNS._AC_SX184_.jpg',
    author: 'Colleen Hoover',
    cover: 'Paperback',
    pages: '379',
    price: '425',
    story:
      'Lowen Ashleigh is a struggling writer on the brink of financial ruin when she accepts the job offer of a lifetime. Jeremy Crawford, husband of bestselling author Verity Crawford, has hired Lowen to complete the remaining books in a successful series his injured wife is unable to finish.',
    ratings: 4,
  },
  {
    id: 5,
    name: '1984!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/41DoIQLHzlL._AC_SX184_.jpg',
    author: 'George Orwell, Erich Fromm',
    cover: 'Mass Market Paperback',
    pages: '629',
    price: '299',
    story:
      'Written more than 70 years ago, 1984 was George Orwell’s chilling prophecy about the future. And while 1984 has come and gone, his dystopian vision of a government that will do anything to control the narrative is timelier than ever...',
    ratings: 4.7,
  },
  {
    id: 6,
    name: 'The Old Farmers!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51tpY0oLw3L._AC_SX184_.jpg',
    author: 'Old Farmer’s Almanac',
    cover: 'Paperback',
    pages: '219',
    price: '100',
    story:
      'Happy New Almanac Year! It’s time to celebrate the 230th edition of The Old Farmer’s Almanac! Long recognized as North America’s most-beloved and best-selling annual, this handy yellow book fulfills every need and expectation as a calendar of the heavens, a time capsule of the year, an essential reference that reads like a magazine. Always timely, topical, and distinctively “useful, with a pleasant degree of humor,” the Almanac is consulted daily throughout the year by users from all walks of life.',
    ratings: 4.6,
  },
  {
    id: 7,
    name: 'The Lord of the Ring!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/41vN31PD7SL._AC_SX184_.jpg',
    author: 'J.R.R. Tolkien',
    cover: 'Hardcover',
    pages: '247',
    price: '250',
    story:
      'J.R.R. Tolkien’s grand masterwork in a new hardcover illustrated with the art created by Tolkien himself as he envisioned Middle-earth',
    ratings: 4,
  },
  {
    id: 8,
    name: 'Once There Were Wolves!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/41V4TQpXGhL._AC_SX184_.jpg',
    author: 'Charlotte McConaghy',
    cover: 'Hardcover',
    pages: '625',
    price: '525',
    story:
      'Show a child just how strong your love is every minute of the day! Features a "To" and "From" personalization page, making this sweet offering an ideal gift for baby showers, birthdays, and new parents. ',
    ratings: 4.8,
  },
  {
    id: 10,
    name: 'The Nature of Middle-earth!',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51RN-ydxniS._AC_SX184_.jpg',
    author: 'J.R.R. Tolkien, Carl F Hostetter',
    cover: 'Hardcover',
    pages: '467',
    price: '488',
    story:
      'The first ever publication of J.R.R. Tolkien’s final writings on Middle-earth, covering a wide range of subjects and perfect for those who have read and enjoyed The Silmarillion, The Lord of the Rings, Unfinished Tales, and The History of Middle-earth, and want to learn more about Tolkien’s magnificent world.',
    ratings: 3.8,
  },
];
